stages:
  - check
  - trigger

check-versions:
  stage: check
  script:
    - apk add --no-cache jq wget
#    - if [ ! -f "stable.txt" ]; then touch stable.txt; fi
#    - if [ ! -f "latest.txt" ]; then touch latest.txt; fi
#    - CUR_STABLE=$(cat stable.txt)
#    - CUR_LATEST=$(cat latest.txt)
    - STABLE=$(wget -qO- https://api.github.com/repos/smallstep/cli/releases | jq -r ".[0].tag_name")
    - LATEST=$(wget -qO- https://api.github.com/repos/smallstep/cli/tags | jq -r ".[0].name")
    - echo "$LATEST" > build-latest.txt
    - echo "LATEST=build" > .env
    - cp .gitlab/latest.yml ./latest.yml
    - if [ "${LATEST}" != "${STABLE}" ]; then echo "$STABLE" > build-stable.txt; cp .gitlab/stable.yml ./stable.yml;  >> .env; fi
  artifacts:
    when: on_success
    paths:
      - build-*.txt
      - stable.yml
      - latest.yml

trigger:latest:
  stage: trigger
  trigger:
    include:
      - artifact: latest.yml
        job: check-versions

trigger:stable:
  allow_failure: true
  stage: trigger
  trigger:
    include:
      - artifact: stable.yml
        job: check-versions
