stages:
  - check
  - trigger

check-versions:
  stage: check
  script:
    - apk add --no-cache jq
    - if [ ! -f "stable.txt" ]; then touch stable.txt; fi
    - if [ ! -f "latest.txt" ]; then touch latest.txt; fi
    - CUR_STABLE=$(cat stable.txt)
    - CUR_LATEST=$(cat latest.txt)
    - STABLE=$(wget -qO- https://api.github.com/repos/smallstep/cli/releases | jq -r ".[0].name")
    - LATEST=$(wget -qO- https://api.github.com/repos/smallstep/cli/tags | jq -r ".[0].name")
    - echo "Stable - ${STABLE} vs ${CUR_STABLE}"
    - echo "Latest - ${LATEST} vs ${CUR_LATEST}"
    - if [ "${STABLE}" != "${CUR_STABLE}" ]; then echo "$STABLE" > build-stable.txt; echo "STABLE=build" > .env; fi
    - if [ "${LATEST}" != "${CUR_LATEST}" ]; then echo "$LATEST" > build-latest.txt; echo "LATEST=build" >> .env; fi
    - if [ "${LATEST}" == "${STABLE}" ]; then rm build-stable.txt; echo "LATEST=build" > .env; fi
  cache:
    key: step-cli.versions
    paths:
      - stable.txt
      - latest.txt
  artifacts:
    when: on_success
    reports:
      dotenv: .env
    paths:
      - build-*.txt

trigger-latest:
  stage: trigger
  needs:
    - check-versions
  trigger:
    include: /.gitlab/latest.yml
    strategy: depend
  rules:
    - if: '$LATEST == "build"'

trigger-stable:
  stage: trigger
  needs:
    - check-versions
  trigger:
    include: /.gitlab/stable.yml
    strategy: depend
  rules:
      - if: '$STABLE == "build"'
