include:
  - local: /.gitlab/shared.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml
  - local: /.gitlab/stable.yml
  - local: /.gitlab/latest.yml
stages:
  - check
  - download
  - build
  - containerize
  - scan
  - create-cache


check-versions:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: never
  stage: check
  script:
    - apk add --no-cache jq wget curl
#    - if [ ! -f "stable.txt" ]; then touch stable.txt; fi
#    - if [ ! -f "latest.txt" ]; then touch latest.txt; fi
#    - CUR_STABLE=$(cat stable.txt)
#    - CUR_LATEST=$(cat latest.txt)
    - STABLE=$(wget -qO- https://api.github.com/repos/smallstep/cli/releases | jq -r ".[0].tag_name")
    - LATEST=$(wget -qO- https://api.github.com/repos/smallstep/cli/tags | jq -r ".[0].name")
    - curl -F token=${CI_JOB_TOKEN} -F ref=master  -F "variables[VERSION]=${LATEST}" -F "variables[BUILD]=latest"  https://gitlab.com/api/v4/projects/19566024/trigger/pipeline
    - if [ "${LATEST}" != "${STABLE}" ]; then curl -F token=${CI_JOB_TOKEN}  -F "variables[VERSION]=${STABLE}" -F "variables[BUILD]=stable" -F ref=master -F https://gitlab.com/api/v4/projects/19566024/trigger/pipeline; fi

cache:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest

