include:
  - local: /.gitlab/shared.yml
  - local: /.gitlab/latest.yml
  - local: /.gitlab/stable.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

stages:
  - check
  - download
  - build
  - containerize
  - scan

check-versions:
  stage: check
  script:
    - apk add --no-cache jq wget
#    - if [ ! -f "stable.txt" ]; then touch stable.txt; fi
#    - if [ ! -f "latest.txt" ]; then touch latest.txt; fi
#    - CUR_STABLE=$(cat stable.txt)
#    - CUR_LATEST=$(cat latest.txt)
    - STABLE=$(wget -qO- https://api.github.com/repos/smallstep/cli/releases | jq -r ".[0].tag_name")
    - LATEST=$(wget -qO- https://api.github.com/repos/smallstep/cli/tags | jq -r ".[0].name")
    - echo "$LATEST" > build-latest.txt
    - echo "LATEST=build" > .env
    - if [ "${LATEST}" != "${STABLE}" ]; then echo "$STABLE" > build-stable.txt; echo "STABLE=build" >> .env; fi
  artifacts:
    when: on_success
    paths:
      - build-*.txt
    reports:
      dotenv: .env
