workflow:
  rules:
    - "$BUILD=stable"

include:
  - local: /.gitlab/shared.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

stages:
  - download
  - build
  - containerize
  - scan

download:latest:
  extends: .download
  before_script:
    - apk add --no-cache grep wget
    - wget -qO- https://api.github.com/repos/smallstep/cli/tags | jq -r ".[0].name" > version.txt

build:armv7:latest:
  needs:
    - download:latest
  variables:
    TYPE: latest
    GIT_STRATEGY: none
    ARCH: arm
    GOARCH: arm
    GOARM: 7
  extends: .build
  tags:
    - native-amd64

build:arm64:latest:
  needs:
    - download:latest
  variables:
    TYPE: latest
    GIT_STRATEGY: none
    ARCH: arm64
    GOARCH: arm64
  extends: .build

build:amd64:latest:
  needs:
    - download:latest
  variables:
    TYPE: latest
    GIT_STRATEGY: none
    ARCH: amd64
    GOARCH: amd64
  extends: .build
  tags:
    - native-amd64

containerize:latest:
  extends: .containerize
  needs:
    - build:amd64:latest
    - build:arm64:latest
    - build:armv7:latest
  variables:
    TYPE: latest

scan:latest:
  needs:
    - job: containerize:latest
      artifacts: false
  extends: .container_scanning
  before_script:
    - export SCANNING_IMAGE_NAME="${CI_REGISTRY_IMAGE}:${VERSION}"
  variables:
    GIT_STRATEGY: none
    NO_OUTPUT: "true"
